### ISSUE TITLE
Doubts about connection

### ISSUE THREAD

**Issue by brainstormi** [bp-ouhaha/EcoForest-modbus-registers#2]
Hi...
    First of all apologize me for my dummy questions, I'm totally newbie in all this ESP32/RS485 and ecogeo stuff. Let me to launch some questions in case you can support me.
    1. You are connecting to the same port BMS2 than e-manager solution from ecoforest. Is it necessary to enable e-manager in the ecogeo menu to make it works.
    2. How do you power the ESP32, externally or do you feed it with 5v out from the controller board? I see the controller has 5v output for sensors, but not sure how much power could deliver or if it could cause any issue with the sensors connected.

![image](https://github.com/user-attachments/assets/39c1a600-3566-4428-b56e-ed3b50afa42f)
    3. I assume that we need to connect to BMS GND port to MAX3485 GND, isn't it?
    4. Is it needed to enable "control by BUS" register in order to be able to write some basic registers, like Mode (5058) in order to power on/off the machine? My concern is what are the implications of enable it regarding how it would delegate certain function like bus heating points... that I don't want to control. I was also looking also to change the mode between summer/winter, but I don't see a register for doing this.
 Thanks in advance for your support.

**Comment by bp-ouhaha** [comment]
Hi and welcome.

Let me try to answer based on my limited knowledge.

1. I use a BMS card that I plugged into the heatpump mainboard. There is already another BMS in use by my TH-Touch room thermostat. Ref: PCOS004850. After plugin in this card, I think I enabled it in the administrator menu, I don't remember. You can configure the communication speed and a few other parameters like parity.
2.  From the BMS card, I start with a twisted pair cable for the Modbus RTU connection. This is only "data", not power. I took a cable of about 1m (actually it's a network cable, SFTP cat6 - I cut the connector and took out 1 pair of twisted wires). I run it through the holes to outside the heatpump -similar to other cables for the heatpump. Once I'm outside, I connect it to RS485-adapter board for ESP. My ESP is powered externally (from a 5V USB phone charger).
3. No we don't need to share ground. The MX3485 has opto-couplers to separate the absolute levels if I remember correctly.
4. No, not needed. I now have 2 "masters", both my ESP and my TH-Touch controlling the heatpump. As long as they don't ask opposite things, it works fine. I didn't see significant conflicts. The TH-Touch interface is "smart enough" to read-back from the heatpump when going through the menus. It doesn't have the tendency to reconfigure things and overwrite changes I did via ESP.

I don't know "how" to change winter/summer, but I know I can observe it.

Best regards,
I hope my answer helps

**Comment by brainstormi** [comment]
Thanks again for your feedback, time to start tinkering.

**Comment by brainstormi** [comment]
Thanks again for your feedback, time to start tinkering.
